name: Simple CI job

on:
  push:
    branches: "*"
  pull_request:
    branches: "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print message to console
        run: |
          echo Sys.time()
