create table tasks (
	id bigint generated by default as identity primary key,
	title varchar(100) not null,
	description varchar(500),
	completed boolean not null default false,
	created_at timestamp not null,
	updated_at timestamp not null,
	due_date date not null,
	priority varchar(20) not null
);

create table task_tags (
	task_id bigint not null,
	tag varchar(64) not null,
	constraint pk_task_tags primary key (task_id, tag),
	constraint fk_task_tags_task foreign key (task_id) references tasks(id) on delete cascade
);

create table task_attachments (
	id bigint generated by default as identity primary key,
	task_id bigint not null,
	file_name varchar(255) not null,
	stored_file_name varchar(255) not null unique,
	content_type varchar(128) not null,
	size bigint not null,
	uploaded_at timestamp not null,
	constraint fk_task_attachments_task foreign key (task_id) references tasks(id) on delete cascade
);

create index idx_task_attachments_task_id on task_attachments(task_id);
create index idx_task_tags_task_id on task_tags(task_id);
create index idx_tasks_due_date on tasks(due_date);

